services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reto-fullstack-backend
    ports:
      - "8000:8000"
    environment:
      - STACKEXCHANGE_URL=https://api.stackexchange.com/2.2/search?order=desc&sort=activity&intitle=perl&site=stackoverflow
    volumes:
      - ./backend/app:/app/app
      - ./certs:/certs:ro
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --ssl-keyfile /certs/localhost.key
      --ssl-certfile /certs/localhost.crt
    restart: unless-stopped